[tool.ruff.lint]
# See: https://docs.astral.sh/ruff/rules/
extend-select = [
  "A", # prevent shadowing builtins
  "COM818", # no trailing commas on bare tuples
  "I",  # isort
  "INP",  # no implicit namespace packages
  "UP",  # pyupgrade
  "W",  # pycodestyle warning
]
extend-ignore = [
  "E501", # ignore line length
]
isort.lines-after-imports = 2
